[package]
name = "itempool"
version = "0.1.0"
edition = "2024"
description = "A simple trait for managing pools of reusable items with discard/recycle support."
license = "MIT OR Apache-2.0"
repository = "https://github.com/caniko/itempool"
readme = "README.md"
keywords = ["gaming", "propability", "random", "bevy"]
categories = ["algorithms", "data-structures", "game-development"]
exclude = [
    ".envrc",
    "flake.nix",
    "flake.lock",
    ".github/",
]

[dependencies]
rand = { version = "^0.9.0", features = ["thread_rng"] }
getrandom = { version = "^0.3.4", features = ["wasm_js"] }

[[example]]
name = "enemy_example"
path = "examples/enemy_example.rs"
